### PR TITLE
Added DEPLOYMENT_REGION_CODE env var

### PR DESCRIPTION
**Pull request by rootik**
@arturek @djfr FYI

### CODE REVIEW

**Comment by VaclavK** [comment]
@djfr is there plan to rename the env? the current name is different - https://github.com/eShopWorld/devops/blob/6ad7d2be285b18479ce12a74ed523544dfd3c7fb/src/Eshopworld.DevOps/EswDevOpsSdk.cs#L25

**Comment by rootik** [comment]
@VaclavK This is additional env var which going to hold short region code
> payments are going to use it to figure out what region they are in to call the lb directly

**Comment by VaclavK** [comment]
@rootik there is devops support for region placement (as per the code link) and I believe it was always meant to contain the code as well so adding new one would not seem good idea

**Comment by djfr** [comment]
@rootik can we get a detailed explanation why are you adding this to the debug scripts that Visual Studio uses to do a local fabric deployment?

**Comment by djfr** [comment]
@rootik we don't do this through Region awareness, we do this through the regional KeyVaults. Those regional URIs are different depending how what KV-region they connect to, and that's how this is designed to work.

Having hardcoded string manipulation code inside components to do URI composition to figure out what DNS entry to call leads to several other problems.

**Comment by VaclavK** [comment]
@rootik have e.g. look at any matching Platform HTTP secrets (
Platform--checkoutApi--HTTP) in e.g. esw-tooling-test-we vs esw-tooling-test-eus

**Comment by rootik** [comment]
@VaclavK @djfr If I understood right this is temporary solution to investigate/mitigate 502s. It will be reverted back.

**Comment by VaclavK** [comment]
can't we release this temp version (which will however kick in for any other pipeline invocation using this task before you revert) from non master branch then - I am not even going to try to understand why this is needed for 502 investigation... 

it seems to be that there is no need to merge into master and therefore PR

**Comment by rootik** [comment]
Ok lads, I'm going to kill it. np

**Pull request closed without merging**
